Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
/tmp/try_flags_nDBcUv.c:4:10: fatal error: cudnn.h: No such file or directory
 #include <cudnn.h>
          ^~~~~~~~~
compilation terminated.

Preallocating 10619/11178 Mb (0.950000) on cuda
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:03:00.0)
/home/halsaied/miniconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using Theano backend.
Traceback (most recent call last):
  File "src/xpRnn.py", line 154, in <module>
    runRSG(30, fileName='rnnCloserRsgGrid.p')
  File "src/xpRnn.py", line 81, in runRSG
    exps = getGrid(fileName)
  File "src/xpRnn.py", line 53, in getGrid
    return pickle.load(open(randomSearchGridPath, 'rb'))
  File "/home/halsaied/miniconda2/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/home/halsaied/miniconda2/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/home/halsaied/miniconda2/lib/python2.7/pickle.py", line 886, in load_eof
    raise EOFError
EOFError
